services:
  ros2:
    container_name: interplanetar_26
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:ro
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - vosk_cache:/root/.cache/vosk
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/root/.Xauthority
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    stdin_open: true
    tty: true
    ipc: host
    privileged: true

volumes:
      vosk_cache:
